# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

format = """
$status\
$sudo\
$env_var\
$shlvl\
$username\
$hostname\
$localip\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$c\
$cmake\
$nodejs\
$conda\
$python\
$rust\
$lua\
$kubernetes\
$docker_context\
$perl\
$php\
$ruby\
$golang\
$cmd_duration\
$memory_usage\
$line_break\
$time\
$character"""

[sudo]
# symbol = "ğŸ§™"
symbol = "ï†† "
disabled = false
style = "red"
# format = '[ï„€ $symbol ï„]($style)'
format = '\[[$symbol]($style)\]'

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '\[[$env_value](white) \]'
variable = "STARSHIP_DISTRO"
disabled = false

[username]
disabled = false
show_always = true
style_user = "bold dimmed blue"
style_root = "white"
format = '\[[$user]($style)\] '

[hostname]
disabled = false
ssh_only = true
style = "white"
format = "<[$hostname]($style)> "
trim_at = ".com"

[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "â€¦/"
# home_symbol = "ïŸ ~"
read_only_style = "197"
read_only = " ï ½"
use_os_path_sep = true
format = "at [$path]($style)[$read_only]($read_only_style) "

[localip]
disabled = true
ssh_only = true
format = "[IP:$localipv4]($style) "

[cmd_duration]
min_time = 500
format = '\[[ï¨ $duration]($style)\]'

[memory_usage]
disabled = false
symbol = "ï¡š "
threshold = 70
format = '\[$symbol[$ram( | $swap)]($style)\]'

[time]
disabled = false
time_format = "%T"
format = '\[[$time]($style)\] '

[c]
symbol = "î˜ "
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[conda]
symbol = "ï„Œ "
ignore_base = false
format = '\[[$symbol$environment](dimmed green)\]'

[kubernetes]
format = '[ï´± $context\($namespace\)](bold purple) '
disabled = false

[docker_context]
symbol = "ïŒˆ "
format = '\[[$symbol$context]($style)\]'

[git_branch]
symbol = "ï¡ "
truncation_symbol = "â€¦/"
style = "bold purple"
always_show_remote = false
format = '\[[$symbol$branch(:$remote_branch)]($style)\]'

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = "bold red"
conflicted = "îœ¨ "
# up_to_date = "ï† "
untracked = "U"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï‘™ "
staged = '[+\($count\)](green)'
renamed = "ï‘š "
deleted = "ï›€ "

[nodejs]
symbol = "îœ˜ "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = "îˆµ "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[rust]
symbol = "î¨ "
format = '\[[$symbol($version)]($style)\]'

[lua]
symbol = "î˜  "
format = '\[[$symbol($version)]($style)\]'

[perl]
symbol = "î© "
format = '\[[$symbol($version)]($style)\]'

[php]
symbol = "î˜ˆ "
format = '\[[$symbol($version)]($style)\]'

[ruby]
symbol = "î‘ "
format = '\[[$symbol($version)]($style)\]'

[golang]
symbol = "î˜§ "
format = '\[[$symbol($version)]($style)\]'

#### Disabled modules ####

# add these back to format if you want them:
[aws]
disabled = true
symbol = "îŒ½  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
[buf]
disabled = true
symbol = "ï’ "
[dart]
disabled = true
symbol = "î˜ "
format = '\[[$symbol($version)]($style)\]'
[dotnet]
disabled = true
[elixir]
disabled = true
symbol = "î‰µ "
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
[elm]
disabled = true
symbol = "î˜¬ "
format = '\[[$symbol($version)]($style)\]'
[erlang]
disabled = true
[helm]
disabled = true
[haskell]
disabled = true
symbol = "î· "
format = '\[[$symbol($version)]($style)\]'
[hg_branch]
disabled = true
symbol = "ï˜ "
format = '\[[$symbol$branch]($style)\]'
[java]
disabled = true
symbol = "î‰– "
format = '\[[$symbol($version)]($style)\]'
[julia]
disabled = true
symbol = "î‰– "
format = '\[[$symbol($version)]($style)\]'
[kotlin]
disabled = true
[nim]
disabled = true
symbol = "ïš¤ "
format = '\[[$symbol($version)]($style)\]'
[nix_shell]
disabled = true
symbol = "ï‹œ "
format = '\[[$symbol$state( \($name\))]($style)\]'
[ocaml]
disabled = true
[package]
disabled = true
symbol = "ï£– "
format = '\[[$symbol$version]($style)\]'
[purescript]
disabled = true
[spack]
disabled = true
symbol = "ğŸ…¢ "
format = '\[[$symbol$environment]($style)\]'
[swift]
disabled = true
[zig]
disabled = true
[gcloud]
disabled = true
[openstack]
disabled = true
[crystal]
disabled = true
[jobs]
disabled = true
[battery]
disabled = true
